Fix

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -55,9 +55,9 @@ jobs:
               run: terraform plan -no-color -input=false -out planfile
               continue-on-error: true
 
-            - name: "Terraform Plan Status"
-              if: steps.plan.outcome == 'failure'
-              run: exit 1
+            # - name: "Terraform Plan Status"
+            #   if: steps.plan.outcome == 'failure'
+            #   run: exit 1
               
             # - name: "Terraform Destroy"
             #   id: destroy
@@ -66,7 +66,7 @@ jobs:
             - name: "Terraform Apply"
               id: apple
               if: github.ref == 'refs/heads/main' && github.event_name == 'push' #  Only Changes on the Main Branch will Apply
-              run: terraform apply -auto-approve # -input=false -parallelism=1 planfile
+              run: terraform apply -auto-approve -input=false -parallelism=1 planfile
 
             - name: Configure AWS credentials
               uses: aws-actions/configure-aws-credentials@v1
